source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'
use_frameworks!
target 'MealPlanner' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
# use_frameworks!

    pod 'CardParts'
  # Pods for MealPlanner

  target 'MealPlannerTests' do
    inherit! :search_paths

    # Pods for testing
  end

  target 'MealPlannerUITests' do
    inherit! :search_paths
    # Pods for testing
  end


end
